name: android

on:
  workflow_dispatch:
  #    inputs:
  #      logLevel:
  #        description: 'Log level'
  #        required: true
  #        default: 'warning'
  #      tags:
  #        required: false
  #        description: 'Test scenario tags'
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ started ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Generate keystore
        run: |
          [ ! -d ~/.android ] && mkdir ~/.android
          echo y | keytool -genkey -dname "cn=debug, ou=debug, o=debug, c=debug" -alias androiddebugkey -keypass android --storepass android -keyalg RSA -keystore ~/.android/debug.keystore -validity 10000

      - name: Replace org.gradle.jvmargs
        run: |
          ORG_GRADLE_JVM=`cat gradle.properties | grep org.gradle.jvmargs`
          sed -i 's/'"${ORG_GRADLE_JVM}"'/org.gradle.jvmargs=-Xmx8192m -Dfile.encoding=UTF-8/g' gradle.properties
          cat gradle.properties | grep org.gradle.jvmargs

      - name: Gradle grant permission
        run: chmod +x gradlew

      - name: Gradle dependencies
        run: ./gradlew dependencies

      - name: Gradle build
        run: ./gradlew clean build

      - name: upload build outputs
        uses: actions/upload-artifact@v2
        with:
          name: outputs
          path: app/build/outputs

      - name: Gradle assembleDebug
        run: ./gradlew clean assembleDebug

      - name: upload assemble debug
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Gradle assembleRelease
        run: ./gradlew clean assembleRelease

      - name: upload assemble release
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk

      - name: Gradle bundleRelease
        run: ./gradlew clean bundleRelease

      - name: upload bundle release
        uses: actions/upload-artifact@v2
        with:
          name: app-aab
          path: app/build/outputs/bundle/release/app-release.aab